### PR TITLE
Run user code in an iframe for extra security

### LINKED ISSUE #175: I can construct arbitrary functions.
If I simply write

``` javascript
Function ("var badcode = 1")();
```

instead of

``` javascript
Function("var badcode=1;")()
```

I can create functions at will.

### LINKED ISSUE #188: Level 15 input allows level jumps
At `player.killedBy()`, writing `player.killedBy(String = {})` causes some serious bugs. 

It first allows you to cross the water without dying (displaying an error each step). On making it across, you get another 'Object is not a function' error when you step on the exit. Despite this, it states at the top "Level 15 solution saved at x", without bringing you to the next level. Continuing to step on the exit will unlock the following level after that for every time you step on it, until all levels are unlocked. Refreshing the page will then bring you directly to the final level. 

Attempting to go back to level 15 afterward, the input section has disappeared, and it is stuck like that.

### LINKED ISSUE #214: Creating custom functions using a copy of Function constructor
One can create custom function using the following approach:

``` javascript
var f = Function;
new f('alert("I am here!");')();
```

### PR DESCRIPTION
**Pull request by pppery**
Instead of trying to prohibit user code from accessing bad functions, simply run the code in a restricted sandbox that doesn't have access to those functions.

Fixes part of #215 (the report given in the first comment no longer works, but the alternate solution by @ChALkeR still does); Fixes #214; Fixes #188;  Fixes #175;  Fixes a lot of other security problems that nobody else bothered to report.

### CODE REVIEW

**Comment by pppery** [comment]
FYI this patch does not close all security vulnerabilities do to the fact that `top` cannot be deleted. The only way I can think of to fix that is to run the entire game in an iframe, which is a bit extreme.

**Comment by AlexNisnevich** [comment]
@pppery This is great work, thanks for doing it!

Since this is a major change, could you double-check that all of the levels (including the bonus levels) still work? I noticed that at least a few of the bonus levels no longer load due to lack of `parseInt` in the global namespace.

**Comment by pppery** [comment]
OK, I confirm that all of the bonus levels load after adding `parseInt` to the allowed function list.

**Comment by pppery** [comment]
I'm usually pretty good about testing my PRs before submitting them (in fact, the original version of this patch did not contain `Date` in `allowedGlobals`, which testing discovered was necessary very quickly, however I didn't think to check bonus levels.
----
Nevertheless, does the fact that some bonus levels depend on functions that the standard levels don't mean that it would be a good idea to add a `extraGlobals` map property?

**Comment by AlexNisnevich** [comment]
An `extraGlobals` map property may be a bit overkill, but is certainly not a bad idea.

**Comment by AlexNisnevich** [comment]
By the way, just out of curiosity, what made you decide to work on tamper-proofing Untrusted? I really appreciate all the work you've done.

**Comment by pppery** [comment]
I suspect it was seeing so many security issues that were very simple for me to fix but had been open for years.

**Pull request merged**
