### PR TITLE
Add no script tag

### PR DESCRIPTION
**Pull request by Camel-lot**
Add noscript tag and message to help in detecting problems on the client side.

### CODE REVIEW

**Comment by neunenak** [comment]
Change "dont" to "don't" and "java-script" to "Javascript" and it'll be good to accept.

**Comment by Camel-lot** [comment]
Done

**Comment by honzi** [comment]
Hello. While I agree this may be better than nothing, I think the wording could be improved as well as `Javascript` being changed to `JavaScript`.

**Comment by AlexNisnevich** [comment]
@honzi - Agreed. Wanna make a PR for it?

**Comment by honzi** [comment]
I can make one if @Camel-lot won't, but it may take me a while because I am not so good at words. I can open a quick one to fix the `Javascript` and save the rest for later, if preferred.

**Pull request merged**
